# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# 테마 설정에 대한 부분입니다. 기본 설정을 유지하였습니다.
#theme                  : "minimal-mistakes-jekyll"
remote_theme           : "mmistakes/minimal-mistakes"

# 스킨을 설정하는 부분입니다.
minimal_mistakes_skin    : "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Build settings
markdown: kramdown


# Site Settings
locale                   : "ko-KR" # 사이트의 언어 설정을 할 수있습니다.
# 표시되는 언어의 내용은 _data/ui-text.yml 에서 수정이 가능합니다.

title: HyoMin's Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.stardocksystems.com/" # the base hostname & protocol for your site, e.g. http://example.com
repository               : "AhnHyoMin/ahnhyomin.github.io" # 블로그 github 리포지토리


author:
  name             : "HyoMin Ahn"
  bio              : "유니티 클라이언트 프로그래머"
  email             : "Hulralra@Gmail.com"
  location         : "Republic of Korea"
  github           : "AhnHyoMin"
  avatar            : /assets/ProfileImage/profile_photo.jpg


include: ["_pages"]

exclude:
  - Gemfile
  - Gemfile.lock

paginate: 5

plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-include-cache

collections:
  project:
    output: true
    permalink: /:collection/:path/
    title: Project
  notes:
    output: true
    permalink: /:collection/:path/
    title: Notes



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      sidebar:
        nav: "posts"
      comments: true
  # _pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true

#google_analytics: "UA-107842956-1"

comments:
  provider: "disqus"
  disqus:
    shortname: "stardocksystems"
